import {lex} from './lexer.js';import {parse} from './parser.js';import {execute} from './interpreter.js';import {examples} from '../examples/examples.js';
const $=id=>document.getElementById(id),code=$('code'),select=$('exampleSelect'),message=$('message');let simulation=null,selected=null;
code.value=examples.factorial;select.onchange=()=>{code.value=examples[select.value];$('args').value=select.value==='suma'?'[10,20,30], 0':select.value==='fibonacci'?'5':'5';reset()};
function reset(){simulation=null;selected=null;$('tree').innerHTML='';$('stack').textContent='Ejecuta una simulación';$('stack').className='stack empty';$('details').textContent='Selecciona un nodo del árbol.';$('details').className='details empty';['calls','depth','base','steps'].forEach(x=>$(x).textContent='0');$('result').textContent='—';$('phase').textContent='EN ESPERA';$('prev').disabled=true;$('next').disabled=true}
function parseArgs(){return $('args').value.split(/,(?![^\[]*\])/).map(x=>{x=x.trim();if(x.startsWith('['))return JSON.parse(x);if(x==='true'||x==='false')return x==='true';return Number(x)})}
function run(){try{const ast=parse(lex(code.value));if(!ast.methods.length)throw Error('No se encontró ningún método.');const entry=ast.methods[0].name;simulation=execute(ast,entry,parseArgs());simulation.cursor=simulation.nodes.length;render();message.className='message';message.textContent='Simulación completada. Haz clic en un nodo para inspeccionar su frame.'}catch(e){message.className='message error';message.textContent=e.message;reset()}}
function render(){const s=simulation;['calls','depth','base','steps'].forEach((x,i)=>$(x).textContent=Object.values(s.stats)[i]);$('result').textContent=Array.isArray(s.result)?JSON.stringify(s.result):String(s.result);$('phase').textContent=s.nodes.some(n=>n.status==='base-case')?'EXPANSIÓN + RETORNO':'RETORNO';const root=s.nodes.find(n=>!n.parentId);$('tree').innerHTML='';if(root)drawTree(root);const active=s.nodes.filter(n=>n.status==='running'||n.status==='returning').slice(-1)[0];const stack=s.nodes.filter(n=>n.id<=((active||s.nodes.at(-1))?.id||0));$('stack').className='stack';$('stack').innerHTML=stack.map(n=>`<div class="frame ${n===active?'active':''}">${n.name}(${n.args.map(format).join(', ')}) ${n.status==='finished'?'✓':''}</div>`).join('');$('prev').disabled=true;$('next').disabled=true}
function format(v){return Array.isArray(v)?`[${v.join(', ')}]`:String(v)}
function drawTree(root){const nodes=[];const walk=(n,x,y)=>{nodes.push({...n,x,y});n.children.forEach((c,i)=>walk(c,x+(i-(n.children.length-1)/2)*150,y+92))};walk(root,Math.max(120,simulation.nodes.length*75),45);const w=Math.max(500,...nodes.map(n=>n.x+130)),h=Math.max(420,...nodes.map(n=>n.y+65));const links=[];nodes.forEach(n=>n.children.forEach(c=>{const child=nodes.find(x=>x.id===c.id);links.push(`<line x1="${n.x}" y1="${n.y+27}" x2="${child.x}" y2="${child.y-27}"/>`)}));const svg=`<svg viewBox="0 0 ${w} ${h}" width="${w}" height="${h}"><g class="links">${links.join('')}</g>${nodes.map(n=>`<g class="node ${n.status}" data-id="${n.id}" transform="translate(${n.x-58},${n.y-27})"><rect width="116" height="54" rx="10"/><text x="58" y="20" text-anchor="middle">${n.name}</text><text x="58" y="38" text-anchor="middle">(${n.args.map(format).join(', ')})</text></g>`).join('')}</svg>`;$('tree').innerHTML=svg;$('tree').querySelectorAll('.node').forEach(el=>el.onclick=()=>show(Number(el.dataset.id)))}
function show(id){selected=simulation.nodes.find(n=>n.id===id);const n=selected;$('details').className='details';$('details').innerHTML=`<dl><dt>Método</dt><dd>${n.name}</dd><dt>Parámetros</dt><dd>${n.args.map(format).join(', ')||'—'}</dd><dt>Variables locales</dt><dd>${Object.entries(n.locals).map(([k,v])=>`${k} = ${format(v)}`).join('<br>')||'ninguna'}</dd><dt>Profundidad</dt><dd>${n.depth}</dd><dt>Estado</dt><dd>${n.status==='base-case'?'CASO BASE':n.status.toUpperCase()}</dd><dt>Retorno</dt><dd>${n.returnValue===undefined?'pendiente':format(n.returnValue)}</dd></dl>`}
function step(delta){if(!simulation){message.className='message error';message.textContent='Primero pulsa Ejecutar.';return}let i=simulation.nodes.indexOf(selected);i=Math.max(0,Math.min(simulation.nodes.length-1,i<0?(delta>0?0:simulation.nodes.length-1):i+delta));show(simulation.nodes[i].id);message.className='message';message.textContent=`Paso ${i+1} de ${simulation.nodes.length}: ${simulation.nodes[i].name}(${simulation.nodes[i].args.map(format).join(', ')})`}
$('run').onclick=()=>{run();$('prev').disabled=false;$('next').disabled=false};$('reset').onclick=()=>{reset();code.focus()};$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);reset();
