import{lex}from'./lexer.js?v=9';import{parse}from'./parser.js?v=9';import{execute}from'./interpreter.js?v=9';import{examples}from'../examples/examples.js?v=9';
const $=id=>document.getElementById(id),code=$('code'),message=$('message');let sim=null,selected=null,cursor=0;
code.value=examples.factorial;$('exampleSelect').onchange=()=>{const k=$('exampleSelect').value;code.value=examples[k];$('args').value=k==='suma'?'[10,20,30], 0':k==='fibonacci'?'5':'5';reset()};
function reset(){sim=null;selected=null;cursor=0;$('tree').innerHTML='';$('stack').className='stack empty';$('stack').textContent='Ejecuta una simulación';$('details').className='details empty';$('details').textContent='Selecciona un nodo del árbol.';['calls','depth','base','steps'].forEach(x=>$(x).textContent='0');$('result').textContent='—';$('phase').textContent='EN ESPERA';$('prev').disabled=true;$('next').disabled=true}
function args(){return $('args').value.split(/,(?![^\[]*\])/).map(x=>{x=x.trim();if(x.startsWith('['))return JSON.parse(x);return x==='true'?true:x==='false'?false:Number(x)})}function fmt(v){return Array.isArray(v)?`[${v.join(', ')}]`:String(v)}
function run(){try{const ast=parse(lex(code.value)),entry=ast.methods[0]?.name;if(!entry)throw Error('No se encontró ningún método.');sim=execute(ast,entry,args());cursor=1;render();message.className='message';message.textContent=`Paso 1 de ${sim.nodes.length}: raíz ${sim.nodes[0].name}(${sim.nodes[0].args.map(fmt).join(', ')})`;$('prev').disabled=true;$('next').disabled=sim.nodes.length<=1}catch(e){reset();message.className='message error';message.textContent=e.message}}
function visible(){const ids=new Set(sim.nodes.filter(n=>n.id<=cursor).map(n=>n.id));return sim.nodes.filter(n=>ids.has(n.id)).map(n=>({...n,children:n.children.filter(c=>ids.has(c.id))}))}
function render(){if(!sim)return;const v=visible();$('calls').textContent=v.length;$('depth').textContent=Math.max(0,...v.map(n=>n.depth+1));$('base').textContent=v.filter(n=>n.status==='base-case').length;$('steps').textContent=cursor;$('result').textContent=cursor===sim.nodes.length?fmt(sim.result):'—';$('phase').textContent=cursor===sim.nodes.length?'RETORNO':'EXPANSIÓN';$('tree').innerHTML='';if(v[0])draw(v[0],v);$('stack').className='stack';$('stack').innerHTML=v.map(n=>`<div class="frame ${n.id===cursor?'active':''}">${n.name}(${n.args.map(fmt).join(', ')}) ${n.id<cursor?'✓':'◉'}</div>`).join('');$('prev').disabled=cursor<=1;$('next').disabled=cursor>=sim.nodes.length}
function draw(root,all){const positioned=[],limit=cursor;const walk=(n,x,y)=>{if(n.id>limit)return;positioned.push({...n,x,y});const kids=n.children.filter(c=>c.id<=limit);kids.forEach((c,i)=>walk(c,x+(i-(kids.length-1)/2)*150,y+92))};walk(root,Math.max(120,all.length*70),45);const w=Math.max(520,...positioned.map(n=>n.x+130)),h=Math.max(420,...positioned.map(n=>n.y+70)),byId=new Map(positioned.map(n=>[n.id,n]));const links=positioned.flatMap(n=>n.children.filter(c=>byId.has(c.id)).map(c=>{const d=byId.get(c.id);return`<line x1="${n.x}" y1="${n.y+27}" x2="${d.x}" y2="${d.y-27}"/>`})).join('');$('tree').innerHTML=`<svg viewBox="0 0 ${w} ${h}" width="${w}" height="${h}"><g class="links">${links}</g>${positioned.map(n=>`<g class="node ${n.id===cursor?'running':n.status}" data-id="${n.id}" transform="translate(${n.x-58},${n.y-27})"><rect width="116" height="54" rx="10"/><text x="58" y="20" text-anchor="middle">${n.name}</text><text x="58" y="38" text-anchor="middle">(${n.args.map(fmt).join(', ')})</text></g>`).join('')}</svg>`;$('tree').querySelectorAll('.node').forEach(e=>e.onclick=()=>show(Number(e.dataset.id)))}
function show(id){if(!sim)return;selected=sim.nodes.find(n=>n.id===id);const n=selected;$('details').className='details';$('details').innerHTML=`<dl><dt>Método</dt><dd>${n.name}</dd><dt>Parámetros</dt><dd>${n.args.map(fmt).join(', ')||'—'}</dd><dt>Variables locales</dt><dd>${Object.entries(n.locals).map(([k,v])=>`${k} = ${fmt(v)}`).join('<br>')||'ninguna'}</dd><dt>Profundidad</dt><dd>${n.depth}</dd><dt>Estado</dt><dd>${n.status==='base-case'?'CASO BASE':n.status.toUpperCase()}</dd><dt>Retorno</dt><dd>${n.returnValue==null?'pendiente':fmt(n.returnValue)}</dd></dl>`}
function step(delta){if(!sim){message.className='message error';message.textContent='Primero pulsa Ejecutar.';return}cursor=Math.max(1,Math.min(sim.nodes.length,cursor+delta));render();const n=sim.nodes[cursor-1];message.className='message';message.textContent=`Paso ${cursor} de ${sim.nodes.length}: ${n.name}(${n.args.map(fmt).join(', ')})`;show(n.id)}
$('run').onclick=run;$('reset').onclick=()=>{reset();code.focus()};$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);reset();
